### ISSUE TITLE
optical communication systems lab. 

### ISSUE THREAD

**Issue by nikitamahoviya** [Yuvraj-kadale/Industrial-Electronics-Lab---ECD-418#4]
Hey @Yuvraj-kadale  !! 
Could you please help us out with the experiments of optical communication systems lab. 
![Screenshot_2021-12-09-09-57-30-827_com google android apps classroom](https://user-images.githubusercontent.com/43717626/145334572-c54f1090-b3af-4249-9809-bbc79064b69f.jpg)

**Comment by Yuvraj-kadale** [comment]
Hey @nikitamahoviya , 

Optical Communication lab [Manual](https://www.bharathuniv.ac.in/colleges1/downloads/courseware_ece/notes/BEC7L2%20-optical%20lab.pdf) might be helpful for you.

Thanks!!!
